version: "3.5"
services:
  db:
    image: mysql:8.0
    command: --lower_case_table_names=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 2sVK7VssY8Pe7UEObSQ20rDyvwxh
    volumes:
      - cache:/data

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - rabbit-log:/var/log/rabbitmq

    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"

  storage:
    image: quay.io/minio/minio
    command: server /data --console-address :9090
    restart: always
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_ACCESS_KEY: "SAO0C6zc"
      MINIO_SECRET_KEY: "PqJ3oqsjL0Inwhy2eXyDR3hpcIHNf5jV"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-storage:/data

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "8080:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-storage:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  mysql-db:
  cache:
  minio-storage:
  smtp4dev-storage:
  rabbit-data:
  rabbit-log:
