name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push-image:
    uses: stacklab-dev-br/github-actions/.github/workflows/dockerhub-build.yml@master
    environment: Staging
    with:
      image: ${{secrets.DOCKERHUB_USERNAME}}/${{vars.DOCKER_IMAGE}}
      tag: "${{ vars.TAG_PREFIX }}-v${{ github.run_number }}"
      dockerfile: "./backend/src/WebAPI/Dockerfile"
      context: "./backend"
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
